[tool.mypy]
exclude = "^(env/|train/)$"
explicit_package_bases = true

[[tool.mypy.overrides]]
module = "onnxruntime.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tensorflow.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tflite_runtime.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = "."
