name: Build Mac App

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download model file
        run: |
          mkdir model
          curl -L -o model/model_100x100.onnx https://github.com/EbinaKai/Sichiribe/releases/download/v0.1.6/model_100x100.onnx

      - name: Rename app.py to Sichiribe.py
        run: |
          mv app.py Sichiribe.py

      - name: Build with Nuitka (MacOS)
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: Sichiribe.py
          standalone: true
          enable-plugins: pyside6
          include-module: matplotlib.backends.backend_qt5agg
          include-data-dir: |
            model=model
            gui/images=gui/images
          macos-create-app-bundle: true
          macos-app-name: Sichiribe
          macos-app-icon: script/Sichiribe_icon.png
          macos-app-protected-resource: "NSCameraUsageDescription:Camera access"

      - name: Fix app bundle structure
        run: |
          cd build
          if [ -d "Resources" ]; then
            mkdir -p Sichiribe.app/Contents/Resources
            mv Resources/* Sichiribe.app/Contents/Resources/
            rm -rf Resources
          fi
          if [ -f "Info.plist" ]; then
            mv Info.plist Sichiribe.app/Contents/
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS Build
          path: |
            build/*.app/**/*
          include-hidden-files: true