name: Build Windows App

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup Build Environment
        uses: ./.github/workflows/setup_environment.yml
        with:
          python-version: 3.12

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: Sichiribe.py
          onefile: true
          standalone: true
          enable-plugins: pyside6
          include-module: matplotlib.backends.backend_qt5agg
          include-data-dir: |
            ./model=model
            ./gui/images=gui/images/splash_image.png
          windows-icon-from-ico: script/Sichiribe_icon.png

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: |
            build/*.exe
          include-hidden-files: true
