name: Build Windows App

on:
  push:
    branches:
      - feature/app/windows  # プッシュ時に実行されるブランチ

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # pipキャッシュの利用
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka tensorflow zstandard imageio

      # Gitのインストールをキャッシュ
      - name: Install Git for Windows if not installed
        run: |
          if (-not (Test-Path "C:/Program Files/Git/bin/bash.exe")) {
            choco install git
          }

      - name: Run bash script
        run: |
          "C:/Program Files/Git/bin/bash.exe" script/build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: ./Sichiribe.dist/
          retention-days: 7  # 7日間だけ保存
